package com.fsj.spring.model.person;
// default package

import java.util.Date;

/**
 * PersonInfo generated by MyEclipse Persistence Tools
 */

public class PersonInfo implements java.io.Serializable {

	// Fields
	// ID
	private Long id;
	//员工编号
	private String piCode;
	//员工姓名
	private String piName;
	//电话
	private String piPhone;
	//手机
	private String piMobile;
	//QQ
	private String piQq;
	//邮件
	private String piEmail;
	//身份证
	private String piIdcard;
	//性别
	private String piSex;
	//入职日期
	private String piJoinDate;
	//出生日期
	private String piBirthDate;
	//学历
	private String piDegree;
	//类型
	private String piType;
	//籍贯
	private String piNation;
	//地址
	private String piAddress;
	//主管人
	private String piSup;
	//组织架构
	private Long piOrg;

	//创建人、创建时间
	private String crtC;

	private String crtDate;
	// Constructors

	/** default constructor */
	public PersonInfo() {
	}

	/** minimal constructor */
	public PersonInfo(Long id) {
		this.id = id;
	}

	/** full constructor */
	public PersonInfo(Long id, String piCode, String piName, String piPhone, String piMobile, String piQq, String piEmail, String piIdcard, String piSex, String piJoinDate, String piBirthDate,
			String piDegree, String piType, String piNation, String piAddress, String piMemo, String piSup, Long piOrg, String crtC, String crtDate) {
		this.id = id;
		this.piCode = piCode;
		this.piName = piName;
		this.piPhone = piPhone;
		this.piMobile = piMobile;
		this.piQq = piQq;
		this.piEmail = piEmail;
		this.piIdcard = piIdcard;
		this.piSex = piSex;
		this.piJoinDate = piJoinDate;
		this.piBirthDate = piBirthDate;
		this.piDegree = piDegree;
		this.piType = piType;
		this.piNation = piNation;
		this.piAddress = piAddress;
		this.piSup = piSup;
		this.piOrg = piOrg;
		this.crtC = crtC;
		this.crtDate = crtDate;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getPiCode() {
		return this.piCode;
	}

	public void setPiCode(String piCode) {
		this.piCode = piCode;
	}

	public String getPiName() {
		return this.piName;
	}

	public void setPiName(String piName) {
		this.piName = piName;
	}

	public String getPiPhone() {
		return this.piPhone;
	}

	public void setPiPhone(String piPhone) {
		this.piPhone = piPhone;
	}

	public String getPiMobile() {
		return this.piMobile;
	}

	public void setPiMobile(String piMobile) {
		this.piMobile = piMobile;
	}

	public String getPiQq() {
		return this.piQq;
	}

	public void setPiQq(String piQq) {
		this.piQq = piQq;
	}

	public String getPiEmail() {
		return this.piEmail;
	}

	public void setPiEmail(String piEmail) {
		this.piEmail = piEmail;
	}

	public String getPiIdcard() {
		return this.piIdcard;
	}

	public void setPiIdcard(String piIdcard) {
		this.piIdcard = piIdcard;
	}

	public String getPiSex() {
		return this.piSex;
	}

	public void setPiSex(String piSex) {
		this.piSex = piSex;
	}

	

	public String getPiJoinDate() {
		return piJoinDate;
	}

	public void setPiJoinDate(String piJoinDate) {
		this.piJoinDate = piJoinDate;
	}

	public String getPiBirthDate() {
		return piBirthDate;
	}

	public void setPiBirthDate(String piBirthDate) {
		this.piBirthDate = piBirthDate;
	}

	public String getPiDegree() {
		return this.piDegree;
	}

	public void setPiDegree(String piDegree) {
		this.piDegree = piDegree;
	}

	public String getPiType() {
		return this.piType;
	}

	public void setPiType(String piType) {
		this.piType = piType;
	}

	public String getPiNation() {
		return this.piNation;
	}

	public void setPiNation(String piNation) {
		this.piNation = piNation;
	}

	public String getPiAddress() {
		return this.piAddress;
	}

	public void setPiAddress(String piAddress) {
		this.piAddress = piAddress;
	}

	public String getPiSup() {
		return this.piSup;
	}

	public void setPiSup(String piSup) {
		this.piSup = piSup;
	}

	public Long getPiOrg() {
		return this.piOrg;
	}

	public void setPiOrg(Long piOrg) {
		this.piOrg = piOrg;
	}

	public String getCrtC() {
		return this.crtC;
	}

	public void setCrtC(String crtC) {
		this.crtC = crtC;
	}

	public String getCrtDate() {
		return this.crtDate;
	}

	public void setCrtDate(String crtDate) {
		this.crtDate = crtDate;
	}

}