package com.fsj.spring.model.sys;
// default package

import java.util.Date;

/**
 * SysMenu generated by MyEclipse Persistence Tools
 */

public class SysMenu implements java.io.Serializable {

	// Fields

	private Long id;

	private String smName;

	private String smCode;

	private String smTitle;

	private String smParent;

	private String smPage;

	private String smContainPage;

	private String smIsUsed;

	private String smIsTop;

	private String smDescription;

	private String crtC;

	private Date crtDate;

	// Constructors

	/** default constructor */
	public SysMenu() {
	}

	/** minimal constructor */
	public SysMenu(Long id) {
		this.id = id;
	}

	/** full constructor */
	public SysMenu(Long id, String smName, String smCode, String smTitle, String smParent, String smPage, String smContainPage, String smIsUsed, String smIsTop, String smDescription, String crtC,
			Date crtDate) {
		this.id = id;
		this.smName = smName;
		this.smCode = smCode;
		this.smTitle = smTitle;
		this.smParent = smParent;
		this.smPage = smPage;
		this.smContainPage = smContainPage;
		this.smIsUsed = smIsUsed;
		this.smIsTop = smIsTop;
		this.smDescription = smDescription;
		this.crtC = crtC;
		this.crtDate = crtDate;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getSmName() {
		return this.smName;
	}

	public void setSmName(String smName) {
		this.smName = smName;
	}

	public String getSmCode() {
		return this.smCode;
	}

	public void setSmCode(String smCode) {
		this.smCode = smCode;
	}

	public String getSmTitle() {
		return this.smTitle;
	}

	public void setSmTitle(String smTitle) {
		this.smTitle = smTitle;
	}

	public String getSmParent() {
		return this.smParent;
	}

	public void setSmParent(String smParent) {
		this.smParent = smParent;
	}

	public String getSmPage() {
		return this.smPage;
	}

	public void setSmPage(String smPage) {
		this.smPage = smPage;
	}

	public String getSmContainPage() {
		return this.smContainPage;
	}

	public void setSmContainPage(String smContainPage) {
		this.smContainPage = smContainPage;
	}

	public String getSmIsUsed() {
		return this.smIsUsed;
	}

	public void setSmIsUsed(String smIsUsed) {
		this.smIsUsed = smIsUsed;
	}

	public String getSmIsTop() {
		return this.smIsTop;
	}

	public void setSmIsTop(String smIsTop) {
		this.smIsTop = smIsTop;
	}

	public String getSmDescription() {
		return this.smDescription;
	}

	public void setSmDescription(String smDescription) {
		this.smDescription = smDescription;
	}

	public String getCrtC() {
		return this.crtC;
	}

	public void setCrtC(String crtC) {
		this.crtC = crtC;
	}

	public Date getCrtDate() {
		return this.crtDate;
	}

	public void setCrtDate(Date crtDate) {
		this.crtDate = crtDate;
	}

}