package com.fsj.spring.model.sys;
// default package


/**
 * SysOrg generated by MyEclipse Persistence Tools
 */

public class SysOrg implements java.io.Serializable {

	// Fields

	private Long id;

	private String soCode;

	private String soName;

	private Long soParent;

	private String crtC;

	private String crtDate;

	// Constructors

	/** default constructor */
	public SysOrg() {
	}

	/** minimal constructor */
	public SysOrg(Long id) {
		this.id = id;
	}

	/** full constructor */
	public SysOrg(Long id, String soCode, String soName, Long soParent, String crtC, String crtDate) {
		this.id = id;
		this.soCode = soCode;
		this.soName = soName;
		this.soParent = soParent;
		this.crtC = crtC;
		this.crtDate = crtDate;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getSoCode() {
		return this.soCode;
	}

	public void setSoCode(String soCode) {
		this.soCode = soCode;
	}

	public String getSoName() {
		return this.soName;
	}

	public void setSoName(String soName) {
		this.soName = soName;
	}

	public Long getSoParent() {
		return this.soParent;
	}

	public void setSoParent(Long soParent) {
		this.soParent = soParent;
	}

	public String getCrtC() {
		return this.crtC;
	}

	public void setCrtC(String crtC) {
		this.crtC = crtC;
	}

	public String getCrtDate() {
		return this.crtDate;
	}

	public void setCrtDate(String crtDate) {
		this.crtDate = crtDate;
	}

}