package com.fsj.spring.model.sys;
// default package

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SysMenu generated by MyEclipse Persistence Tools
 */

public class SysMenu implements java.io.Serializable {

	// Fields

	private Long id;

	private String smName;

	private String smCode;

	private String smTitle;

	//private String smParent;
	
	private SysMenu parentMenu;

	private String smPage;

	private String smContainPage;

	private String smIsUsed;

	private String smIsTop;

	private String smDescription;

	private String crtC;

	private Date crtDate;
	
	private Set<SysMenuOper> sysMenuOpers = new HashSet<SysMenuOper>(0);

	public SysMenu() {
		super();
	}

	public SysMenu(Long id, String smName, String smCode, String smTitle, String smParent, String smPage, String smContainPage, String smIsUsed, String smIsTop, String smDescription, String crtC, Date crtDate, Set<SysMenuOper> sysMenuOpers) {
		super();
		this.id = id;
		this.smName = smName;
		this.smCode = smCode;
		this.smTitle = smTitle;
		//this.smParent = smParent;
		this.smPage = smPage;
		this.smContainPage = smContainPage;
		this.smIsUsed = smIsUsed;
		this.smIsTop = smIsTop;
		this.smDescription = smDescription;
		this.crtC = crtC;
		this.crtDate = crtDate;
		this.sysMenuOpers = sysMenuOpers;
	}

	public String getCrtC() {
		return crtC;
	}

	public void setCrtC(String crtC) {
		this.crtC = crtC;
	}

	public Date getCrtDate() {
		return crtDate;
	}

	public void setCrtDate(Date crtDate) {
		this.crtDate = crtDate;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getSmCode() {
		return smCode;
	}

	public void setSmCode(String smCode) {
		this.smCode = smCode;
	}

	public String getSmContainPage() {
		return smContainPage;
	}

	public void setSmContainPage(String smContainPage) {
		this.smContainPage = smContainPage;
	}

	public String getSmDescription() {
		return smDescription;
	}

	public void setSmDescription(String smDescription) {
		this.smDescription = smDescription;
	}

	public String getSmIsTop() {
		return smIsTop;
	}

	public void setSmIsTop(String smIsTop) {
		this.smIsTop = smIsTop;
	}

	public String getSmIsUsed() {
		return smIsUsed;
	}

	public void setSmIsUsed(String smIsUsed) {
		this.smIsUsed = smIsUsed;
	}

	public String getSmName() {
		return smName;
	}

	public void setSmName(String smName) {
		this.smName = smName;
	}

	public String getSmPage() {
		return smPage;
	}

	public void setSmPage(String smPage) {
		this.smPage = smPage;
	}

//	public String getSmParent() {
//		return smParent;
//	}
//
//	public void setSmParent(String smParent) {
//		this.smParent = smParent;
//	}

	public String getSmTitle() {
		return smTitle;
	}

	public void setSmTitle(String smTitle) {
		this.smTitle = smTitle;
	}

	public Set<SysMenuOper> getSysMenuOpers() {
		return sysMenuOpers;
	}

	public void setSysMenuOpers(Set<SysMenuOper> sysMenuOpers) {
		this.sysMenuOpers = sysMenuOpers;
	}

	public SysMenu getParentMenu() {
		return parentMenu;
	}

	public void setParentMenu(SysMenu parentMenu) {
		this.parentMenu = parentMenu;
	}


}