package com.fsj.spring.model.sys;
// default package

import java.util.Date;

/**
 * SysRole generated by MyEclipse Persistence Tools
 */

public class SysRole implements java.io.Serializable {

	// Fields

	private Long id;

	private String srCode;

	private String srName;

	private String srMemo;

	private String crtC;

	private Date crtDate;

	// Constructors

	/** default constructor */
	public SysRole() {
	}

	/** minimal constructor */
	public SysRole(Long id) {
		this.id = id;
	}

	/** full constructor */
	public SysRole(Long id, String srCode, String srName, String srMemo, String crtC, Date crtDate) {
		this.id = id;
		this.srCode = srCode;
		this.srName = srName;
		this.srMemo = srMemo;
		this.crtC = crtC;
		this.crtDate = crtDate;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getSrCode() {
		return this.srCode;
	}

	public void setSrCode(String srCode) {
		this.srCode = srCode;
	}

	public String getSrName() {
		return this.srName;
	}

	public void setSrName(String srName) {
		this.srName = srName;
	}

	public String getSrMemo() {
		return this.srMemo;
	}

	public void setSrMemo(String srMemo) {
		this.srMemo = srMemo;
	}

	public String getCrtC() {
		return this.crtC;
	}

	public void setCrtC(String crtC) {
		this.crtC = crtC;
	}

	public Date getCrtDate() {
		return this.crtDate;
	}

	public void setCrtDate(Date crtDate) {
		this.crtDate = crtDate;
	}

}