package com.fsj.spring.model.sys;
// default package


/**
 * SysUser generated by MyEclipse Persistence Tools
 */

public class SysUser implements java.io.Serializable {

	// Fields

	private Long id;

	private String suUsername;

	private String suPassword;

	private String suNameCn;

	private String suAccEna;

	private String suMemo;

	private String crtC;

	private String crtDate;

	// Constructors

	/** default constructor */
	public SysUser() {
	}

	/** minimal constructor */
	public SysUser(Long id) {
		this.id = id;
	}

	/** full constructor */
	public SysUser(Long id, String suUsername, String suPassword, String suNameCn, String suAccEna, String suMemo, String crtC, String crtDate) {
		this.id = id;
		this.suUsername = suUsername;
		this.suPassword = suPassword;
		this.suNameCn = suNameCn;
		this.suAccEna = suAccEna;
		this.suMemo = suMemo;
		this.crtC = crtC;
		this.crtDate = crtDate;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getSuUsername() {
		return this.suUsername;
	}

	public void setSuUsername(String suUsername) {
		this.suUsername = suUsername;
	}

	public String getSuPassword() {
		return this.suPassword;
	}

	public void setSuPassword(String suPassword) {
		this.suPassword = suPassword;
	}

	public String getSuNameCn() {
		return this.suNameCn;
	}

	public void setSuNameCn(String suNameCn) {
		this.suNameCn = suNameCn;
	}

	public String getSuAccEna() {
		return this.suAccEna;
	}

	public void setSuAccEna(String suAccEna) {
		this.suAccEna = suAccEna;
	}

	public String getSuMemo() {
		return this.suMemo;
	}

	public void setSuMemo(String suMemo) {
		this.suMemo = suMemo;
	}

	public String getCrtC() {
		return this.crtC;
	}

	public void setCrtC(String crtC) {
		this.crtC = crtC;
	}

	public String getCrtDate() {
		return this.crtDate;
	}

	public void setCrtDate(String crtDate) {
		this.crtDate = crtDate;
	}

}